name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_TOKEN }}
    - run: |
      docker build . --file Dockerfile -t ${{ secrets.ACR_SERVER }}
      docker push ${{ secrets.ACR_SERVER }}
      
     
      
      
