name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Github Checkout
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.VB6DEMO_DEPLOY }}
      
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_TOKEN }}
    - run: |
        docker build . --file Dockerfile -t ${{ secrets.ACR_SERVER }}/vbdemo:${{ github.sha }}
        docker push ${{ secrets.ACR_SERVER }}/vbdemo:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: DockerVB6
        dns-name-label: url-for-container
        image: ${{ secrets.ACR_SERVER }}/vbdemo:${{ github.sha }}
        registry-username: ${{ secrets.ACR_PULL_USER }}
        registry-password: ${{ secrets.ACR_PULL_TOKEN }}
        name: vb6-demo-deploy
        location: 'east us'
        os-type: Windows