name: Docker Image CI

on:
  push:
    branches: [ githubactions-ccc ]
  pull_request:
    branches: [ githubactions-ccc ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vb-demo:$(date +%s)
